---

sudo: required

language: bash

services:
  - docker

install:
  - docker build -t blazegraph:2.1.4 2.1.4/
  - docker run --name blazegraph -d -p 8080:8080 blazegraph:2.1.4

before_script:
  - sleep 30

script:
  - docker ps | grep blazegraph
  - curl http://localhost:8080/bigdata/#query
